services:
  misp-ioc-fetcher:
    image: mispiocfetcher:latest
    build:
      context: ..
      dockerfile: docker/build/Dockerfile
    volumes:
      - ./ioc:/app/ioc
    env_file:
      - .env
    restart: always